markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Max Prokopiev
url: http://maxprokopiev.com
description: Developer, juggler and good man
twitter: mprokopiev
github: juggler
gravatar_url: http://www.gravatar.com/avatar/88054fc582a42bf05c3f8460f84ffcee
